local-http:
	INTERFACE=HTTP python3 src/main.py

local-cmd:
	INTERFACE=CMD python3 src/main.py

local-cmd-v2:
	python3 src/live_yolo_ocr.py

local-cmd-v2-model:
	python3 src/live_yolo_ocr.py --model "$(MODEL)" --device "$(or $(DEVICE),0)"

local-cmd-v2-stream:
	python3 src/live_yolo_ocr.py --model "$(MODEL)" --device "$(DEVICE)" --interval $(or $(INTERVAL),1)

local-cron:
	INTERFACE=CRON python3 src/main.py

local-cmd-stream:
	INTERFACE=CMD python3 src/main.py -- --device "$(DEVICE)" --interval $(or $(INTERVAL),3)

install:
	pip3 install --break-system-packages -r requirements.txt

install-ocr:
	pip3 install --break-system-packages -r requirements.txt \
		--extra-index-url https://download.pytorch.org/whl/cpu
	pip3 install --break-system-packages python-bidi pyclipper ninja scipy scikit-image shapely

generate-swagger:
	@echo "Swagger auto-generated by FastAPI at /docs"
	@echo "Static OpenAPI spec at: src/docs/http/swagger.yaml"

seed:
	python3 src/scripts/seed.py

seed-api-keys:
	python3 src/scripts/seed_api_key.py

help:
	@echo "Available commands:"
	@echo "  make local-http              Start HTTP API server (port 3000)"
	@echo "  make local-cmd               Start live OCR v1 (webcam, EasyOCR only)"
	@echo "  make local-cmd-v2            Start live OCR v2 (webcam, YOLO generic)"
	@echo "  make local-cmd-v2-model MODEL=models/plate_best.pt"
	@echo "  make local-cmd-v2-stream MODEL=models/plate_best.pt DEVICE=rtsp://... INTERVAL=1"
	@echo "  make local-cron              Start CRON scheduler (dues reminder)"
	@echo "  make local-cmd-stream DEVICE=rtsp://... INTERVAL=3"
	@echo "  make install                 Install API dependencies"
	@echo "  make install-ocr             Install OCR + API dependencies"
	@echo "  make generate-swagger        Info about swagger docs"
	@echo "  make seed                    Seed database with sample data"
	@echo "  make seed-api-keys           Generate initial admin + device API keys"
